require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AffiliateLinksController do

  # This should return the minimal set of attributes required to create a valid
  # AffiliateLink. As you add validations to AffiliateLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AffiliateLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all affiliate_links as @affiliate_links" do
      affiliate_link = AffiliateLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:affiliate_links).should eq([affiliate_link])
    end
  end

  describe "GET show" do
    it "assigns the requested affiliate_link as @affiliate_link" do
      affiliate_link = AffiliateLink.create! valid_attributes
      get :show, {:id => affiliate_link.to_param}, valid_session
      assigns(:affiliate_link).should eq(affiliate_link)
    end
  end

  describe "GET new" do
    it "assigns a new affiliate_link as @affiliate_link" do
      get :new, {}, valid_session
      assigns(:affiliate_link).should be_a_new(AffiliateLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested affiliate_link as @affiliate_link" do
      affiliate_link = AffiliateLink.create! valid_attributes
      get :edit, {:id => affiliate_link.to_param}, valid_session
      assigns(:affiliate_link).should eq(affiliate_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AffiliateLink" do
        expect {
          post :create, {:affiliate_link => valid_attributes}, valid_session
        }.to change(AffiliateLink, :count).by(1)
      end

      it "assigns a newly created affiliate_link as @affiliate_link" do
        post :create, {:affiliate_link => valid_attributes}, valid_session
        assigns(:affiliate_link).should be_a(AffiliateLink)
        assigns(:affiliate_link).should be_persisted
      end

      it "redirects to the created affiliate_link" do
        post :create, {:affiliate_link => valid_attributes}, valid_session
        response.should redirect_to(AffiliateLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved affiliate_link as @affiliate_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        AffiliateLink.any_instance.stub(:save).and_return(false)
        post :create, {:affiliate_link => { "title" => "invalid value" }}, valid_session
        assigns(:affiliate_link).should be_a_new(AffiliateLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AffiliateLink.any_instance.stub(:save).and_return(false)
        post :create, {:affiliate_link => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested affiliate_link" do
        affiliate_link = AffiliateLink.create! valid_attributes
        # Assuming there are no other affiliate_links in the database, this
        # specifies that the AffiliateLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AffiliateLink.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => affiliate_link.to_param, :affiliate_link => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested affiliate_link as @affiliate_link" do
        affiliate_link = AffiliateLink.create! valid_attributes
        put :update, {:id => affiliate_link.to_param, :affiliate_link => valid_attributes}, valid_session
        assigns(:affiliate_link).should eq(affiliate_link)
      end

      it "redirects to the affiliate_link" do
        affiliate_link = AffiliateLink.create! valid_attributes
        put :update, {:id => affiliate_link.to_param, :affiliate_link => valid_attributes}, valid_session
        response.should redirect_to(affiliate_link)
      end
    end

    describe "with invalid params" do
      it "assigns the affiliate_link as @affiliate_link" do
        affiliate_link = AffiliateLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AffiliateLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => affiliate_link.to_param, :affiliate_link => { "title" => "invalid value" }}, valid_session
        assigns(:affiliate_link).should eq(affiliate_link)
      end

      it "re-renders the 'edit' template" do
        affiliate_link = AffiliateLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AffiliateLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => affiliate_link.to_param, :affiliate_link => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested affiliate_link" do
      affiliate_link = AffiliateLink.create! valid_attributes
      expect {
        delete :destroy, {:id => affiliate_link.to_param}, valid_session
      }.to change(AffiliateLink, :count).by(-1)
    end

    it "redirects to the affiliate_links list" do
      affiliate_link = AffiliateLink.create! valid_attributes
      delete :destroy, {:id => affiliate_link.to_param}, valid_session
      response.should redirect_to(affiliate_links_url)
    end
  end

end
